# Generated by Django 4.2 on 2025-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topics',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
